export const actionTypes = {
    LOADING_CONTACTS: 'LOADING_CONTACTS',
    SELECT_CONTACT: 'SELECT_CONTACT',
    LOADING_CONTACTS_SUCCESS: 'LOADING_CONTACTS_SUCCESS',
    LOADING_CONTACTS_FAILURE: 'LOADING_CONTACTS_FAILURE',
    SELECT_CONTACTS_PAGE: 'SELECT_CONTACTS_PAGE',
    UPDATE_CONTACT_LIST: 'UPDATE_CONTACT_LIST',
    SEARCH_CONTACT: 'SEARCH_CONTACT',
    CHANGE_SORT_STATUS: 'CHANGE_SORT_STATUS',
};