export const actionTypes = {
    LOADING_CONTACTS: 'LOADING_CONTACTS',
    SELECT_CONTACT: 'SELECT_CONTACT',
    LOADING_CONTACTS_SUCCESS: 'LOADING_CONTACTS_SUCCESS',
    LOADING_CONTACTS_FAILURE: 'LOADING_CONTACTS_FAILURE',
    SELECT_CONTACTS_PAGE: 'SELECT_CONTACTS_PAGE',
};